mongo:
  uri: mongodb://localhost:27017/db

oauth2:
  base_url: http://localhost:8000
  keys:
    - key_file: key.private
      algorithm: RS256
      use: sig
      publish: true
      id: 'RS256'
  #issuer: jdav-freiburg.de
  issuer: "http://localhost:8000"

  token_length: 48
  token_expiration:
    authorization_code: 86400
    implicit: 3600
    refresh_token: 3600
    password: 86400
    client_credentials: 86400
    session: 31536000

  authorization_code_length: 48

  user:
    properties:
      email:
        type: str
        format: '^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
        can_edit: self
      email_verified:
        type: bool
        can_edit: admin
      phone_number:
        type: str
        format: '^((\+[0-9]{2}[- /\.]?([1-9][0-9]{2,5}))|(0[0-9]{3,4}))[-\s\./0-9]*[0-9]$'
        can_edit: self
      phone_number_verified:
        type: bool
        can_edit: admin
      name:
        type: str
        template: "{given_name.lower()}.{family_name.lower()}"
      family_name:
        type: str
        title: Family Name
        format: '^[\p{L} -]+$'
        can_edit: self
      given_name:
        type: str
        title: Given Name
        format: '^[\p{L} -]+$'
        can_edit: self
      # middle_name
      # nickname
      preferred_username:
        type: str
        template: "{given_name.lower()}.{family_name.lower()}"
      profile:
        type: str
      picture:
        type: picture
        title: Picture
        can_edit: self
      # website
      # gender
      # birthdate
      # zoneinfo
      locale:
        type: enum
        title: Language
        can_edit: self
        values:
          - value: de_de
            title: Deutsch
          - value: en_us
            title: English
      updated_at:
        type: datetime
      password:
        type: password
        title: Password
        can_edit: self
        pwned_password_check: true
      card_id:
        type: str
        can_edit: self
        format: '^[0-9a-fA-F]*$'
    scopes:
      email:
        - email
        - email_verified
      phone:
        - phone_number
        - phone_number_verified
      profile:
        - name
        - family_name
        - given_name
        # middle_name
        # nickname
        - preferred_username
        - profile
        - picture
        # website
        # gender
        # birthdate
        # zoneinfo
        - locale
        - updated_at
    password:
      schemes: ['argon2', 'bcrypt', 'pbkdf2_sha256']

manager:
  backend_base_url: http://localhost:8000/manager
  frontend_base_url: http://localhost:4200
  secret_key: 'blablabla'

  oauth2:
    server_metadata_url: 'http://localhost:8000/.well-known/openid-configuration'
    client_id: 'manager'
    client_secret: 'client1secret'
