mongo:
  uri: mongodb://127.0.0.1:27017/db

oauth2:
  base_url: 'http://127.0.0.1:8000'
  mail_domain: 'localhost.localdomain'
  mail_api_key: '0123456789'
  keys:
    - key_file: key.private
      algorithm: RS256
      use: sig
      publish: true
      id: 'RS256'
  issuer: 'http://127.0.0.1:8000'

  card_authentication_api_key:
  card_authentication_client_id:

  token_length: 48
  token_expiration:
    authorization_code: 86400
    implicit: 3600
    refresh_token: 3600
    password: 86400
    client_credentials: 86400
    session: 31536000
  access_token_length: 32
  authorization_code_length: 48

  use_german_username_translation: true

  login_throttler:
    enable: true
    base_delay: 0.1
    max_delay: 30
    # 1 day
    reset_cutoff: 86400
    skip_private: true

  password:
    schemes: ['argon2', 'bcrypt', 'pbkdf2_sha256']
    pwned_password_check: true

manager:
  backend_cors_origin: ['http://127.0.0.1:4200']
  backend_base_url: http://127.0.0.1:8000/manager
  frontend_base_url: http://127.0.0.1:4200
  secret_key: 'blablabla'
  name: 'User Manager'

  token_valid:
    # registration: 86400
    registration: 15552000
    email_set: 86400
    password_reset: 86400

  oauth2:
    server_metadata_url: 'http://127.0.0.1:8000/.well-known/openid-configuration'
    client_id: 'manager'

  mail:
    host: localhost
    sender: 'admin@localhost'
    port: null
    ssl: false
    starttls: false
    keyfile: null
    certfile: null
    user: null
    password: null
