mongo:
  uri: mongodb://127.0.0.1:27017/db

oauth2:
  base_url: "http://127.0.0.1:8000"
  mail_domain: "localhost.localdomain"
  mail_api_key: "0123456789"
  keys:
    - key_file: key.private
      algorithm: RS256
      use: sig
      publish: true
      id: 'RS256'
  issuer: "http://127.0.0.1:8000"

  card_authentication_api_key:
  card_authentication_client_id:

  token_length: 48
  token_expiration:
    authorization_code: 86400
    implicit: 3600
    refresh_token: 3600
    password: 86400
    client_credentials: 86400
    session: 31536000
  access_token_length: 32
  authorization_code_length: 48

  use_german_username_translation: true

  login_throttler:
    enable: true
    base_delay: 0.1
    max_delay: 30
    # 1 day
    reset_cutoff: 86400
    skip_private: true

  user:
    properties:
      separator:
        type: separator
      sub:
        type: str
        title: "User ID"
      active:
        type: bool
        title: "Active"
        default: false
        can_edit: admin
        can_read: self
        visible: admin
      email:
        type: email
        title: "E-Mail"
        required: true
        format: '^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
        format_help: "ab@c.de"
        can_edit: self
      email_verified:
        type: bool
        title: "E-Mail Verified"
        can_edit: admin
        visible: nobody
      phone_number:
        type: str
        title: "Phone"
        required: true
        format: '^((\+[0-9]{2}[- /\.]?([1-9][0-9]{2,5}))|(0[0-9]{3,4}))[-\s\./0-9]*[0-9]$'
        format_help: "+49 1234 56789"
        can_edit: self
      phone_number_verified:
        type: bool
        title: "Phone Verified"
        can_edit: admin
      name:
        type: str
        title: "Display Name"
        visible: admin
        template: "{given_name} {family_name}"
      family_name:
        type: str
        title: "Family Name"
        required: true
        format: '^[\p{L} -]+$'
        format_help: "printable characters"
        can_edit: self
      given_name:
        type: str
        title: "Given Name"
        required: true
        format: '^[\p{L} -]+$'
        format_help: "printable characters"
        can_edit: self
      # middle_name
      # nickname
      preferred_username:
        # This is generated in the backend from 'name'
        type: str
        title: "Preferred Username (ID)"
        visible: admin
        can_edit: nobody
        can_read: admin
        write_once: true
        template: "{make_username(name)}"
      profile:
        type: str
        title: "Profile URL"
        visible: nobody
      picture:
        type: picture
        title: "Picture"
        can_edit: self
      # website
      gender:
        type: enum
        title: "Gender"
        can_edit: self
        required: true
        values:
          - value: female
            title: "Female"
          - value: male
            title: "Male"
          - value: non-binary
            title: "Non-Binary"
          - value: undefined
            title: "No Answer"
      birthdate:
        type: date
        title: "Date of Birth"
        can_edit: self
        can_read: self
        required: true
        # format: '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
        # format_help: "1900-01-01 (year-month-day)"
      zoneinfo:
        type: enum
        title: "Zone Info"
        default: Europe/Berlin
        values:
          - value: Europe/Berlin
            title: Europe/Berlin
        can_edit: self
        can_read: self
        visible: admin
      locale:
        type: enum
        title: "Preferred Language"
        can_edit: self
        can_read: self
        values:
          - value: de_de
            title: Deutsch
          - value: en_us
            title: English
      address.street_address:
        type: str
        title: "Street Address"
        required: true
        can_edit: self
        can_read: self
      address.locality:
        type: str
        title: 'City'
        required: true
        can_edit: self
        can_read: self
      address.region:
        type: str
        title: 'State/Province'
        can_edit: self
        can_read: self
      address.postal_code:
        type: str
        title: "Postal Code"
        required: true
        can_edit: self
        can_read: self
      address.country:
        type: enum
        title: "Country"
        can_edit: self
        can_read: self
        default: germany
        required: true
        values:
          - value: germany
            title: Germany
          - value: switzerland
            title: Switzerland
          - value: france
            title: France
      updated_at:
        type: datetime
        title: "Updated At"
        visible: admin
        can_read: self
      password:
        type: password
        title: "Password"
        required: true
        can_edit: self
        can_read: nobody
      storage_quota:
        type: int
        title: "Storage Quota"
        can_edit: admin
        can_read: self
        format: '^[0-9]+$'
        default: 100000000
      has_email_alias:
        type: bool
        title: "Enable E-Mail Alias"
        can_edit: admin
        can_read: self
        visible: nobody
        default: false
      forward_emails:
        type: bool
        title: "Forward E-Mails to registered E-Mail"
        can_edit: admin
        can_read: self
        visible: nobody
        default: true
      has_postbox:
        type: bool
        title: "Enable Postbox"
        can_edit: admin
        can_read: self
        default: false
      postbox_quota:
        type: int
        title: "E-Mail Postbox Quota"
        can_edit: admin
        can_read: self
        format: '^[0-9]+$'
        default: 100000000
      groups:
        type: groups
        title: "Groups"
        default: ['users']
        can_edit: admin
        can_read: self
      access_tokens:
        type: access_tokens
        title: "Access Tokens"
        default: []
        can_edit: admin
        can_read: admin
      email_allowed_forward_groups:
        type: groups
        title: "Allow Forward E-Mail"
        default: []
        can_edit: admin
        can_read: self
        visible: nobody
      email_forward_groups:
        type: groups
        title: "Forward E-Mail"
        default: []
        can_edit: self
        can_read: self
        visible: nobody
      email_postbox_access_groups:
        type: groups
        title: "Access Postbox"
        default: []
        can_edit: admin
        can_read: self
        visible: nobody
      email_alias:
        # This is generated once
        type: str
        title: "E-Mail Alias"
        visible: nobody
        can_edit: nobody
        can_read: self
        write_once: true
        template: "{preferred_username.lower()}@{config.oauth2.mail_domain.lower()}"
      notes:
        type: multistr
        title: "Admin Notes"
        can_edit: admin
        can_read: admin
      card_id:
        type: str
        title: "Card ID"
        can_edit: self
        can_read: admin
        visible: admin
        format: '^[0-9a-fA-F]*$'
    scopes:
      profile:
        title: "Profile"
        properties:
          - name
          - family_name
          - given_name
          # - middle_name
          # - nickname
          - preferred_username
          - profile
          - picture
          # - website
          # - gender
          # - birthdate
          - zoneinfo
          # - 'address.street_address'
          # - 'address.locality'
          # - 'address.region'
          # - 'address.postal_code'
          # - 'address.country'
      email:
        title: "E-Mail"
        properties:
          - email
          - email_verified
      phone:
        title: "Phone"
        properties:
          - phone_number
          - phone_number_verified
      gender:
        title: "Gender"
        properties:
          - 'gender'
      groups:
        title: "Groups"
        properties:
          - 'groups'
      users:
        title: "Other Users Profile"
        properties:
          - name
          - family_name
          - given_name
          - picture
          - email
          - phone_number
      birthdate:
        title: "Birthdate"
        properties:
          - 'birthdate'
      address:
        title: "Address"
        properties:
          - 'address.street_address'
          - 'address.locality'
          - 'address.region'
          - 'address.postal_code'
          - 'address.country'
      storage_quota:
        title: "Storage Quota"
        properties:
          - storage_quota
    password:
      schemes: ['argon2', 'bcrypt', 'pbkdf2_sha256']
      pwned_password_check: true

manager:
  backend_cors_origin: []
  backend_base_url: http://127.0.0.1:8000/manager
  frontend_base_url: http://127.0.0.1:4200
  secret_key: 'blablabla'
  name: "User Manager"

  token_valid:
    # registration: 86400
    registration: 15552000
    email_set: 86400
    password_reset: 86400

  oauth2:
    server_metadata_url: 'http://127.0.0.1:8000/.well-known/openid-configuration'
    client_id: 'manager'

  list:
    - email
    - given_name
    - family_name
    - phone_number
    - active

  view:
    - picture
    - email
    - password
    - active
    - email_verified
    - preferred_username
    - name
    - given_name
    - family_name
    - phone_number
    - phone_number_verified
    - zoneinfo
    - locale
    - birthdate
    - gender
    - address.street_address
    - address.locality
    - address.region
    - address.postal_code
    - address.country
    - storage_quota
    - separator
    - has_email_alias
    - email_alias
    - forward_emails
    - has_postbox
    - postbox_quota
    - separator
    - notes
    - groups
    - access_tokens
    - email_allowed_forward_groups
    - email_forward_groups
    - email_postbox_access_groups
    - updated_at
    - card_id

  registration:
    - picture
    - email
    - password
    - separator
    - given_name
    - family_name
    - phone_number
    - separator
    - birthdate
    - gender
    - separator
    - address.street_address
    - address.postal_code
    - address.locality
    - address.region
    - address.country
    - active
